# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_demokit_pro'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_demokit_pro'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["dbt_demokit_pro/models"]
analysis-paths: ["dbt_demokit_pro/analyses"]
test-paths: ["dbt_demokit_pro/tests"]
seed-paths: ["dbt_demokit_pro/seeds"]
macro-paths: ["dbt_demokit_pro/macros"]
snapshot-paths: ["dbt_demokit_pro/snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "dbt_demokit_pro/target"
  - "dbt_demokit_pro/dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbt_demokit_pro:
    work:
      +materialized: view
      +schema: offybi              # reads from offybi (your default)
    mart:
      +materialized: table
      +schema: mart         # ← writes dim/fact here
